name = "Logic"
license = "MIT"
licenselink = "https://github.com/chasinglogic/logic/blob/master/LICENSE.md"
description = "A simple theme for bloggers with a Github."
homepage = "http://chasinglogic.io/"
tags = ["blog", "syntax", "code", "programming", "github", "analytics"]
features = ["google-analytics", "share", "syntax-highlighting"]
min_version = 0.17

[author]
  name = "Mathew Robinson"
  homepage = "http://chasinglogic.io"
